### ISSUE TITLE
Adtechmedia main page changes

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#102]
https://xd.adobe.com/view/50d8e7ad-b3de-479c-8219-6664d2701809/

**Comment by avozicov** [comment]
<img width="1280" alt="screen shot 2017-05-02 at 15 00 48" src="https://cloud.githubusercontent.com/assets/12330493/25616933/41fde8f4-2f48-11e7-9836-b60cee9a0a10.png">
<img width="1280" alt="screen shot 2017-05-02 at 15 00 55" src="https://cloud.githubusercontent.com/assets/12330493/25616934/42094aa0-2f48-11e7-84d2-bd0f6c6b3d06.png">
<img width="1280" alt="screen shot 2017-05-02 at 15 01 14" src="https://cloud.githubusercontent.com/assets/12330493/25616935/420d2030-2f48-11e7-94c9-2c6b0fc99a10.png">
