### ISSUE TITLE
Optimize js files after redesign

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#108]

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-14 at 19 09 57" src="https://user-images.githubusercontent.com/12330493/28220450-27c642a6-68c8-11e7-902b-77bcf4b33e55.png">
<img width="1280" alt="screen shot 2017-07-14 at 19 09 59" src="https://user-images.githubusercontent.com/12330493/28220452-27cf9414-68c8-11e7-98df-58a0b47a6364.png">
<img width="1280" alt="screen shot 2017-07-14 at 19 10 01" src="https://user-images.githubusercontent.com/12330493/28220451-27ce6080-68c8-11e7-913c-51ee872d6b95.png">
<img width="1280" alt="screen shot 2017-07-14 at 19 10 02" src="https://user-images.githubusercontent.com/12330493/28220453-27cff760-68c8-11e7-8330-9c1bfed6e86e.png">
<img width="1280" alt="screen shot 2017-07-14 at 19 09 55" src="https://user-images.githubusercontent.com/12330493/28220454-27d2cc7e-68c8-11e7-9047-f22fbdb83509.png">
<img width="1280" alt="screen shot 2017-07-14 at 19 09 56" src="https://user-images.githubusercontent.com/12330493/28220455-27d2fa5a-68c8-11e7-9bec-1396308c783a.png">
