### ISSUE TITLE
Change header & footer on all static pages

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#109]

**Comment by avozicov** [comment]
<img width="1280" alt="screen shot 2017-05-02 at 15 06 15" src="https://cloud.githubusercontent.com/assets/12330493/25617054/010f34aa-2f49-11e7-809f-585c7a71827d.png">

<img width="1280" alt="screen shot 2017-05-02 at 15 06 22" src="https://cloud.githubusercontent.com/assets/12330493/25617057/04a0b3b4-2f49-11e7-8e72-973db0533ebe.png">
