### ISSUE TITLE
Scroll down button changes

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#112]
![scroll down button](https://cloud.githubusercontent.com/assets/8668196/25614451/a2792152-2f3a-11e7-9bc0-a050dd905538.png)

**Comment by icovali** [comment]
When main slide in visible: 
- Scroll down button should point downwards, on click should slide to the next section

When main slide is not visible:
- Scroll down button should point upwards, on click should slide to the top of the page

**Comment by avozicov** [comment]
Task will be tested once code will be deployed to dev env

**Comment by avozicov** [comment]
<img width="1280" alt="screen shot 2017-05-04 at 13 52 44" src="https://cloud.githubusercontent.com/assets/12330493/25700583/0061dd94-30d1-11e7-8e0f-826787bcfd29.png">
<img width="1280" alt="screen shot 2017-05-04 at 13 52 51" src="https://cloud.githubusercontent.com/assets/12330493/25700584/0062c646-30d1-11e7-8968-7f5d8745fef8.png">
