### ISSUE TITLE
Refactor modal animations

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#113]

**Comment by avozicov** [comment]
@icovali  Note that blur effect is also missing on modal animation for any pop-up
_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-04-27 at 11 44 55" src="https://cloud.githubusercontent.com/assets/12330493/25475307/032039dc-2b3f-11e7-9b44-1ca930981db6.png">

**Comment by avozicov** [comment]
<img width="1280" alt="screen shot 2017-05-22 at 16 23 03" src="https://cloud.githubusercontent.com/assets/12330493/26310831/f3c4001a-3f0a-11e7-8d00-9975c41691d2.png">
