### ISSUE TITLE
Watch Now video modal

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#117]

**Comment by icovali** [comment]
- video block: https://madeby.google.com/home/

- `watch now` button animations : https://drive.google.com/file/d/0ByfACE4FxdLzUVhIb09qeklmTW8/view?usp=sharing

**Comment by avozicov** [comment]
<img width="1280" alt="screen shot 2017-05-12 at 18 43 02" src="https://cloud.githubusercontent.com/assets/12330493/26005801/dd1e3fb2-3742-11e7-82c7-f62898a537ef.png">
