### ISSUE TITLE
Social cards image

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#126]
![social-image-100](https://cloud.githubusercontent.com/assets/8668196/25661292/b306fccc-3018-11e7-977f-45bbfe1b8a6c.jpg)

**Comment by avozicov** [comment]
Following issue can be validated only after **Prod** Deploy

**Comment by avozicov** [comment]
Confirmation Testing is failed.
_Please refer to attachment for more details:_

<img width="507" alt="screen shot 2017-05-05 at 12 38 38" src="https://cloud.githubusercontent.com/assets/12330493/25740625/f872f1f8-318f-11e7-8e29-f77c9d5e7aa2.png">

**Comment by icovali** [comment]
This is a possible cache related issue, as the updated image has the same name as old one. When running the url through Facebook Debugger, the updated image is shown:

![screen shot 2017-05-05 at 13 30 32](https://cloud.githubusercontent.com/assets/8668196/25742201/1621c830-3197-11e7-8e63-bafacfd29ab6.png)

Also I've opened a ticket at facebook community:
https://www.facebook.com/help/community/question/?id=127474544468126&added&rdrhc

If there are no changes on their end till our next prod deploy, I'll alter the image's name.

**Comment by avozicov** [comment]
Test actions for the following task can be performed only on Prod Environment

**Comment by avozicov** [comment]
<img width="504" alt="screen shot 2017-05-12 at 18 28 30" src="https://cloud.githubusercontent.com/assets/12330493/26005141/d8048c40-3740-11e7-9a7a-bcc030172ea6.png">

<img width="509" alt="screen shot 2017-05-12 at 18 29 55" src="https://cloud.githubusercontent.com/assets/12330493/26005198/0757f856-3741-11e7-8946-c1c2d05d41ac.png">
