### ISSUE TITLE
Optimize sass files after redesign

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#132]
Optimize sass files after redesign

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- main css file should divided by application component
https://github.com/AdTechMedia/adtechmedia-website/commit/8e5a9b7d1e98800a7dde589d4e8b0bbb8a19e5b6
https://github.com/AdTechMedia/adtechmedia-website/tree/master/src/adtechmedia-website/frontend/sass
