### ISSUE TITLE
Request a Demo changes

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#134]
Refactor mailchimp provided code:
- display only custom `Thank You` page after submitting the form
- remove `Later` button

Please refer bellow for "Thank You" page design :
https://xd.adobe.com/view/50d8e7ad-b3de-479c-8219-6664d2701809/

**Comment by ivignan** [comment]
cc @irca20

**Comment by irca20** [comment]
Design is ready, you can proceed to implementation

**Comment by icovali** [comment]
@ddimitrioglo Please display `/demo-confirmation` page after submitting the form

**Comment by avozicov** [comment]
Implemented "Thank you" page
<img width="1280" alt="screen shot 2017-05-18 at 15 54 55" src="https://cloud.githubusercontent.com/assets/12330493/26203181/e9b30164-3be2-11e7-8356-b790a122e927.png">

Removed "Later" button
<img width="311" alt="screen shot 2017-05-18 at 15 56 21" src="https://cloud.githubusercontent.com/assets/12330493/26203203/012d47a0-3be3-11e7-95d6-bc955b56b006.png">
