### ISSUE TITLE
[mobile view] "Request a demo" action can not be performed on mobile device

### ISSUE THREAD

**Issue by avozicov** [AdTechMedia/adtechmedia-website#136]
_Steps to reproduce:_
1. Navigate "home" page
2. Click on "Request a Demo" button 
3. Fill the required fields on "Request a demo" form with valid data
4. Click on "Get Started" button 

_BUG:_
- Request is not sent by the click on "Get Started" button

_Note:_
- Bug is reproducing on IOS 9.3.5 
- "First name" field placeholder is still visible after filling with data

_Please refer to attachment for more details:_

![request a demo](https://cloud.githubusercontent.com/assets/12330493/25952644/eb3d16b0-3669-11e7-9985-d4f099c480e3.jpg)

**Comment by ivignan** [comment]
Minor priority as it is related to old iOS 9 version

**Comment by avozicov** [comment]
Bug is not reproduced anymore.
Tested on IOS 9.3.5
