### ISSUE TITLE
[mobile-view] Notification message is not displayed on "Contact" form submission 

### ISSUE THREAD

**Issue by avozicov** [AdTechMedia/adtechmedia-website#140]
_Steps to reproduce:_
1. Navigate "Contact" page
2. Fill the required form fields with valid data
4. Click on "Submit" button 

_BUG:_
- Notification message is not displayed on "Contact" form submission

_Note:_
- Bug is reproducing on IOS 9.3.5 iPad

**Comment by ddimitrioglo** [comment]
@avozicov
I can not reproduce it, please check it in new www-dev environment

**Comment by avozicov** [comment]
@ddimitrioglo Bug is reproduced with different behavior:
- Request can not be submitted from iPad (IOS 9.3.5)

**Comment by AlexandrUrita** [comment]
Issue is reproducible. After clicking on Submit button nothing happening.
@ivignan Please advise if this task should be closed w/o any further investigation/fix because that issue is reproduced only on 9.3.5 IOS
Thank you.

**Comment by AlexandrUrita** [comment]
Talked with Igor. Task can be closed.
