### ISSUE TITLE
Watch Now video changes

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#148]
- video block: https://madeby.google.com/home/

- watch now button animations : https://drive.google.com/file/d/0ByfACE4FxdLzUVhIb09qeklmTW8/view?usp=sharing

**Comment by avozicov** [comment]
![watchnow](https://cloud.githubusercontent.com/assets/12330493/26152950/f89ab07c-3b11-11e7-81cf-df13cb4d07bb.gif)
