### ISSUE TITLE
'Uncaught SyntaxError: Unexpected token <' error

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/adtechmedia-website#15]
Error is displayed in console every time, please refer to attachment:
`Uncaught SyntaxError: Unexpected token <`

![screenshot from 2016-09-28 18 37 34](https://cloud.githubusercontent.com/assets/10956412/18920669/c8944b62-85aa-11e6-8841-43d5bea8e851.png)

**Comment by mgoria** [comment]
Solved into consolidated app

**Comment by eistrati** [comment]
Verified.
