### ISSUE TITLE
Wrong icon on Chrome tab

### ISSUE THREAD

**Issue by AlexandrUrita** [AdTechMedia/adtechmedia-website#151]
Description: There are two types of icons that are displayed on Chrome tab. One type is for Blog section. Other type is on rest pages of the site

Steps to reproduce:
1. Open Chrome and navigate to adtechmedia.io
2. Open new tab in Chrome and navigate to https://blog.adtechmedia.io/
3. Compare icons of the opened tabs

Expected result: Icons should be the same

Actual result: Icons are different.
Please refer to the screenshots below:
![screen shot 2017-05-16 at 12 58 06](https://cloud.githubusercontent.com/assets/27765884/26100928/04cf7826-3a38-11e7-92ee-6c98af00654d.png)
![screen shot 2017-05-16 at 12 58 27](https://cloud.githubusercontent.com/assets/27765884/26100930/073b9d4c-3a38-11e7-87f5-d596b4787bf9.png)

**Comment by avozicov** [comment]
<img width="603" alt="screen shot 2017-05-17 at 15 22 22" src="https://cloud.githubusercontent.com/assets/12330493/26153584/b21d29ba-3b14-11e7-876a-b560fdffb513.png">
<img width="588" alt="screen shot 2017-05-17 at 15 22 12" src="https://cloud.githubusercontent.com/assets/12330493/26153583/b21b44c4-3b14-11e7-812f-7c168d214e6c.png">
