### ISSUE TITLE
Getting Started menu is not highlighted for User Guide

### ISSUE THREAD

**Issue by AlexandrUrita** [AdTechMedia/adtechmedia-website#157]
Description: On the User Guide page some Bullets from Getting Started menu are not highlighted from Step3

Steps to Reproduce:
1. Open Adtechmedia.io
2. Navigate to https://www-dev.adtechmedia.io/api/
3. Click on the MORE button that is located on the RIGHT side of the page
4. Scroll down the page till Step3 of the Guide

Expected result: Bullet point should be highlighted as for previous steps
![screen_shot_2017-05-18_at_12_11_00](https://cloud.githubusercontent.com/assets/27765884/26195551/dc7e462a-3bc4-11e7-99ad-34bbe1697c04.png)

Actual result: Bullet point is not highlighted 
![screen_shot_2017-05-18_at_12_14_48](https://cloud.githubusercontent.com/assets/27765884/26195604/00dfd3bc-3bc5-11e7-8ff6-eb7572da5d14.png)

**Comment by icovali** [comment]
- Fixed scroll issue

- By clicking _second to last_ menu item, the _active_ state will not be added, as it has little content

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- Top-left menu item should be highlighted on scroll and on click 
<img width="1280" alt="screen shot 2017-06-12 at 09 50 47" src="https://user-images.githubusercontent.com/12330493/27022022-a5213464-4f54-11e7-8ea2-bd648d5d5725.png">
