### ISSUE TITLE
Larger window breaks down style of User Guide page

### ISSUE THREAD

**Issue by AlexandrUrita** [AdTechMedia/adtechmedia-website#158]
Description: After some investigation with the team we notice that User Guide page works different ways for different window sizes. For Smaller page no issues are detected. For that page was used - http://ricostacruz.com/flatdoc/ which has same issues. There could be a solution like adding blank area when window will be enlarge. Please find below steps to reproduce:

Steps to reproduce:
1. Open adtechmedia.io
2. Navigate to https://www-dev.adtechmedia.io/user-guide/ 
3. Make some resizing of window to see how page is modifying 

Result for smaller window:
![screen shot 2017-05-18 at 12 29 01](https://cloud.githubusercontent.com/assets/27765884/26196172/d1876dbc-3bc6-11e7-9c53-5dc3ccabb6ad.png)

Result for bigger window:
![screen shot 2017-05-18 at 12 29 11](https://cloud.githubusercontent.com/assets/27765884/26196192/e07a3a8e-3bc6-11e7-8511-72e395604d28.png)

**Comment by ivignan** [comment]
It is ok for now
