### ISSUE TITLE
Register link leads to Admin console if user already in the system

### ISSUE THREAD

**Issue by AlexandrUrita** [AdTechMedia/adtechmedia-website#160]
Description: When user login to the system and want to register another user he cannot do that w/o logout. Register link will always leading to Admin console page
Main idea is allow user register another one w/o logging out from system

Steps to reproduce:
0. Prerequisites: User should not be in the system
1. Open adtechmedia.io
2. Navigate to Admin page -> https://www-dev.adtechmedia.io/admin/
3. Click on Returning Customer and enter credentials.
4. Navigate to -> https://www-dev.adtechmedia.io/case-studies/
5. Click on Register link

Expected result: User should be navigated to Admin page with suggestion of registering a new user

Actual result: User will be navigate to private Account tab. 
Note: Ones user is logged in page /admin will be unavailable. Redirection will be applied. Please find on a screenshot below /admin page
![screen shot 2017-05-18 at 13 06 47](https://cloud.githubusercontent.com/assets/27765884/26197459/e7ceacee-3bca-11e7-99bf-caeeb3cc11a9.png)

**Comment by ddimitrioglo** [comment]
@AlexandrUrita Please discuss this issue with @mgoria 
In case if it makes sense please move it into deep-account repo.
Looks like we should change auth guard:
```
  {
    path: 'signup',
    component: AuthComponent,
    canActivate: [Guards.UnauthenticatedCanActivateGuard],
  },
```

**Comment by AlexandrUrita** [comment]
We had a discussion with @mgoria. 
@eistrati could you please advise for a behaviour of Register link if user is already login to the system.
Currently if session is running Register link leads to https://www-dev.adtechmedia.io/admin/ with user in it. There is no opportunity to Register a new user w/o breaking the session manually.
Some potential solutions:
1. Deactivate Register link if user already in the system
2. Register link breaks session and user has opportunity to register other user
3. Leave it as it is, only add copy that a warn that if a user is in the system link will behave as login link.

**Comment by eistrati** [comment]
I think if user is already logged in and clicks on Register, it's fine for him/her to be redirected into Admin without registration. We can consider this issue not relevant and close it.

**Comment by AlexandrUrita** [comment]
@eistrati Regarding latest updates and connection between WP plugin and Adtechmedia site we have this scenario:
1. User has registration on WP with plugin with -> email1@sample.com
2. Same user logged into adtechmedia site with -> email2@sample.com
3. When User tries to register a plugin with email1 he/she will be redirected to website with logged into system with email2. 
There will be misrepresentation that user activated that plugin for email1.
