### ISSUE TITLE
Styles are broken on "Request a demo" form

### ISSUE THREAD

**Issue by avozicov** [AdTechMedia/adtechmedia-website#162]
_Pre-requisites:_
- email used for "demo request" should be already used before 

_Steps to reproduce:_
- Navigate to "Request a demo" form 
- Fill the "email" input field with the previously used email
- Submit the request

_Note:_
- Styles are also broken when request is submitted for new user (attachment 2)

_Please refer to attachment for more details:_
<img width="309" alt="screen shot 2017-05-18 at 15 58 44" src="https://cloud.githubusercontent.com/assets/12330493/26203354/8813ea3a-3be3-11e7-8f45-33b0dabdc975.png">

![message](https://cloud.githubusercontent.com/assets/12330493/26317824/753bb2da-3f21-11e7-9156-26eae395de5d.gif)

**Comment by ddimitrioglo** [comment]
As a hotfix i've fixed is like this:
```
.text-field__label {
  max-width: 225px;
}

.text-field__label.valid {
  position: relative !important;
  line-height: 22px;
}

.text-field__label.error {
  position: relative !important;
  line-height: 22px;
  color: red !important;
}

.text-field__label.error > a {
  text-decoration: underline;
  pointer-events: auto;
}
```
@icovali please review & rewrite it

**Comment by avozicov** [comment]
Test Passed 
<img width="1280" alt="screen shot 2017-05-30 at 16 17 49" src="https://cloud.githubusercontent.com/assets/12330493/26585067/b8ff6056-4553-11e7-94e5-afb1e003d952.png">
