### ISSUE TITLE
Header animations

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#163]
_on scroll down:_
Remove sticky state

_on scroll up:_
Add sticky state

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- Sticky state for header should be disabled on scroll down and should be enabled on scroll up
<img width="1280" alt="screen shot 2017-06-12 at 09 52 18" src="https://user-images.githubusercontent.com/12330493/27022108-0f53dc60-4f55-11e7-826e-64f405454262.png">
<img width="1280" alt="screen shot 2017-06-12 at 09 52 21" src="https://user-images.githubusercontent.com/12330493/27022107-0f5345d4-4f55-11e7-8c2a-d7eaf0c941ad.png">
