### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#164]
Minify .css and .js files
Compress images where possible

**Comment by eistrati** [comment]
@icovali Check this out: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.adtechmedia.io%2F

**Comment by avozicov** [comment]
Overall site Performance is still required to be improved.
Actual result is :
Desktop = 81%
Mobile = 68%

Acceptance Criteria for the following issues is ~ 80%-90% for basic performance test from the link bellow 
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.adtechmedia.io%2F&tab=desktop

**Comment by icovali** [comment]
As per [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww-dev.adtechmedia.io%2F&tab=desktop), the following issues were found:

- **Leverage browser caching**
might be done on AWS side

- **Minify HTML**
might be added together with .js files into pre-deploy hook

- **Reduce server response time**
might be done on AWS side

- **Eliminate render-blocking and CSS in above-the-fold content**
The provided solutions (defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML) are not really feasible, as the core .css files are at stake.

@ivignan please re-assign this task to someone from backend team, to take care of highlighted issues.

**Comment by avozicov** [comment]
Task is still in Progress and is not ready for testing.

**Comment by ddimitrioglo** [comment]
Following Google's [recommendations](https://developers.google.com/speed/pagespeed/insights/) I could reach 91 of 100 on my test site:

- Enable compression - `Done` [cloudfront side];
- Leverage browser caching - `Done` [s3 side];
- Minify CSS - `Done` [manually] (BUT it should be done on the deploy step, to avoid braking development experience);
- Minify JavaScript - `Done` [manually] (the same as Minify CSS);
- Optimize images - `Done` [manually] (It's up to designer and not always applicable);
- Asynchronously load blocking resources - `Skipped` (it's hard to control load order of JS);
- Including critical portions of css directly in the HTML - `Skipped` (this needs full styles refactoring)

**Summary**: moving css and js to the bottom of the page increases page speed but brakes UX (html first - styles after)

Question: @eistrati taking this tests in consideration, what are requirements for page speed?

![pagespeed](https://user-images.githubusercontent.com/9005667/27860642-2051ed02-6186-11e7-83c2-5a98c9712d56.gif)

**Comment by eistrati** [comment]
First approach - https://developers.google.com/web/fundamentals/getting-started/codelabs/your-first-pwapp/

**Comment by ddimitrioglo** [comment]
I've moved back-end part to another issues and fixed them.
@icovali you can continue working on it (see comments above)

**Comment by AlexandrUrita** [comment]
FYI: Test actions cannot be performed because of the new approach of environments. Manage and website are separate in test env. Developers are working now to resolve related issues
Blocked by: https://github.com/MitocGroup/atm/issues/1107

**Comment by avozicov** [comment]
- According Google page speed reporter there are still some possible optimizations left.
<img width="846" alt="screen shot 2017-07-20 at 12 29 46" src="https://user-images.githubusercontent.com/12330493/28410788-70112818-6d47-11e7-80b4-0877174c0312.png">

Overall performance was increased:
Mobile from 68% to 71%



@icovali Could you please review it and provide details if it can be implemented on your side?

**Comment by icovali** [comment]
Moved .css files to the bottom of the document with `lazyload` attr added.  Only `main.css` file with default styling was left in `head` section

**Comment by avozicov** [comment]
According Google page speed reporter there are still some possible optimizations left.
Please review all the pages.
<img width="775" alt="screen shot 2017-07-25 at 16 19 50" src="https://user-images.githubusercontent.com/12330493/28574261-16f10f38-7156-11e7-937b-611bee7e74c8.png">
<img width="964" alt="screen shot 2017-07-25 at 16 20 38" src="https://user-images.githubusercontent.com/12330493/28574260-16f048d2-7156-11e7-922a-707fe66fddab.png">

**Comment by eistrati** [comment]
Closed.
