### ISSUE TITLE
Revenue calculator UI

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#170]
https://xd.adobe.com/view/50d8e7ad-b3de-479c-8219-6664d2701809/screen/dcdf7e92-9930-43a0-9009-6e47b92f77e5/calculator

**Comment by icovali** [comment]
Pages were added as follows:

- `/calculator`
https://xd.adobe.com/view/50d8e7ad-b3de-479c-8219-6664d2701809/screen/dcdf7e92-9930-43a0-9009-6e47b92f77e5/calculator/

- `/calculator-result`
https://xd.adobe.com/view/50d8e7ad-b3de-479c-8219-6664d2701809/screen/edc92870-2e9a-4fcd-b022-eb10b50e729d/calculator-1

-  `/calculator-confirmation`
https://xd.adobe.com/view/50d8e7ad-b3de-479c-8219-6664d2701809/screen/b98f7544-0706-47b9-8e26-7208334d8c45/calculator-thank-you

**Comment by eistrati** [comment]
Add link on text "$35 billion by 2020" and reference here: https://www.ovum.com/research/ad-blocking-forecast-report-2015-20/

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- pages view on website should meet required design provided from task description 
- responsive design should be implemented 
- links to blog should be opened on new tab by the click 
- validation for the required fields should be implemented and triggered by the form submit 

Note:
- testing actions for the actual task are related only to UI part of the pages

Please refer to attachment for more details:
<img width="1280" alt="screen shot 2017-06-08 at 18 13 56" src="https://user-images.githubusercontent.com/12330493/26936780-385bc68e-4c78-11e7-95fa-c27597508b41.png">
<img width="622" alt="screen shot 2017-06-08 at 18 13 58" src="https://user-images.githubusercontent.com/12330493/26936781-385f89e0-4c78-11e7-941b-85eecccaec6f.png">
<img width="1280" alt="screen shot 2017-06-08 at 18 14 51" src="https://user-images.githubusercontent.com/12330493/26936778-385880aa-4c78-11e7-96dd-b240bb22e8c4.png">
<img width="1280" alt="screen shot 2017-06-08 at 18 15 53" src="https://user-images.githubusercontent.com/12330493/26936779-38598cd4-4c78-11e7-8758-9c8919eb946d.png">
