### ISSUE TITLE
There is no blur effect when clicking inside a modal

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#172]
<img width="1140" alt="screen shot 2017-05-26 at 16 22 53" src="https://cloud.githubusercontent.com/assets/8668196/26496317/a42cac5a-422f-11e7-879d-b6c7f06b93a3.png">

**Comment by avozicov** [comment]
Test Passed
<img width="1280" alt="screen shot 2017-05-30 at 16 12 02" src="https://cloud.githubusercontent.com/assets/12330493/26584791/be3371d0-4552-11e7-8ed0-de0dd2dd774f.png">
