### ISSUE TITLE
Blog posts section on Calculator confirmation page

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#179]
**UI**: 
https://xd.adobe.com/view/50d8e7ad-b3de-479c-8219-6664d2701809/screen/b98f7544-0706-47b9-8e26-7208334d8c45/calculator-thank-you

**Posts**:
https://blog.adtechmedia.io/adblocking-is-a-growing-problem-for-publishers-or-is-it-700ddecdbf6e

https://blog.adtechmedia.io/subscriptions-vs-micropayments-which-is-better-for-publishers-8b8fffa52261

https://blog.adtechmedia.io/what-are-micropayments-how-can-they-help-bloggers-monetize-their-content-4ccf3e40dea0

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- Links are displayed on Calculator confirmation
- Links are opened in new tab by the click 
- Valid blog posts articles are displayed when accessing links
<img width="1280" alt="screen shot 2017-06-09 at 15 16 37" src="https://user-images.githubusercontent.com/12330493/26975016-b06c57d4-4d26-11e7-8f14-a2ae64e62a43.png">
