### ISSUE TITLE
not-found page issues

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#182]
not-found page issues after ui changes
![screen shot 2017-06-05 at 15 07 59](https://cloud.githubusercontent.com/assets/8668196/26783846/fd10d5d2-4a02-11e7-98b2-c0b0322659ed.png)

**Comment by avozicov** [comment]
**Test Passed**
- Page style should not be broken
<img width="1280" alt="screen shot 2017-06-12 at 09 57 04" src="https://user-images.githubusercontent.com/12330493/27022200-9113ec5e-4f55-11e7-9cbc-b7050beea27f.png">
