### ISSUE TITLE
Request a demo popup jumps on mobile devices

### ISSUE THREAD

**Issue by AlexandrUrita** [AdTechMedia/adtechmedia-website#185]
Description: After clicking on mobile devices on Request a demo popup it jumps down and cannot be closed with one click at [X] mark

Steps to reproduce:
1. Navigate to https://www-dev.adtechmedia.io
2. Switch browser to Responsive design mode
3. Select any of the device
4. On the site click on Request a Demo button
5. Click on any text field

Expected result: Field is active. Popup stick on its place

Actual result: Field is active. Popup jumps down

Note: Popup cannot be closed with one click on [X] mark -> restores initial position 
![popup issue](https://cloud.githubusercontent.com/assets/27765884/26789511/3161ed38-4a19-11e7-82fc-a22b0d1cae60.gif)

**Comment by icovali** [comment]
- Restored default IOS behavior for focused inputs, needed to keep them in viewport when keyboard is open:
<img width="377" alt="keyboard"  src="https://user-images.githubusercontent.com/8668196/26885580-b24e4f3e-4bab-11e7-8a96-2c9b293c6435.png">

- First click is for input to loose focus and keyboard to hide

**Comment by avozicov** [comment]
Task is considered resolved according comments provided by developer.
