### ISSUE TITLE
Migrate to Material Design Icons

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#196]
Migrate from Font Awesome to Material Design Icons

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-21 at 11 59 03" src="https://user-images.githubusercontent.com/12330493/28456793-32866358-6e0c-11e7-9710-d6f729c20f5c.png">
<img width="1280" alt="screen shot 2017-07-21 at 11 52 22" src="https://user-images.githubusercontent.com/12330493/28456798-350d43bc-6e0c-11e7-97c6-69a0e2916263.png">
