### ISSUE TITLE
Validation is not applied on "Contact" form 

### ISSUE THREAD

**Issue by avozicov** [AdTechMedia/adtechmedia-website#198]
Note: 
- Bug seems to be reproduced on some outdated version of Safari browser including Version 10.0.2 (11602.3.12.0.1)
- Bug was tested also on latest Version 10.1.1 (12603.2.4) and is not reproduced 

1. Access adtechmedia-website 
2.Navigate to "Contact" form
3.Leave the required fields empty 
4.Submit the request 

BUG:
- Request can be submitted in spite the fact that required fields are empty

**Comment by AlexandrUrita** [comment]
Issue is no longer reproducible. Re-Check was made on safari 10.0.2. and latest version 10.1.1 Moving to done
