### ISSUE TITLE
"Terms of Use" and "Privacy Policy" links can not be accessed because of the "Pure Chat" modal

### ISSUE THREAD

**Issue by avozicov** [AdTechMedia/adtechmedia-website#200]
_Steps to reproduce:_
- Access the adtechmedia-website
- Scroll down to the footer and wait until "Pure Chat" will be displayed 

_BUG:_
- "Terms of Use" and "Privacy Policy" links can not be accessed because of the "Pure Chat" modal is overlaps footer area 

_Enhancement:_
- Reduce the width of "Pure Chat" modal and use the empty space from bottom right corner to place the modal in the way it does not hide the footer elements 

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-06-12 at 19 11 00" src="https://user-images.githubusercontent.com/12330493/27043479-e3d4a08a-4fa2-11e7-98c2-bd92e8a1ca18.png">

**Comment by ivignan** [comment]
We will look into other chat options. Chat disabled for now
