### ISSUE TITLE
Change video link on home page

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#201]
Please change asap the link on www.adtechmedia.io home page to the following video: https://youtu.be/lMfUpyDQ0dk

Updated on `/wordpress-plugin` page as well

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- the following video should be displayed by the click on "Watch now" button
https://www.youtube.com/watch?v=lMfUpyDQ0dk&feature=youtu.be

<img width="1280" alt="screen shot 2017-06-13 at 17 57 12" src="https://user-images.githubusercontent.com/12330493/27090085-e3efee18-5064-11e7-9866-7dd13c7dec07.png">
