### ISSUE TITLE
add latest blog post to AdTechMedia.io site footer

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#211]
https://xd.adobe.com/view/50d8e7ad-b3de-479c-8219-6664d2701809/

**Comment by avozicov** [comment]
**Test Failed**
- There is an issues with "Follow" button on Safari browser 
Please refer to attachment for more details
<img width="1277" alt="screen shot 2017-06-22 at 17 39 23" src="https://user-images.githubusercontent.com/12330493/27439941-e7eae978-5771-11e7-83e8-67a5cec8b15f.png">

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-06-23 at 11 45 11" src="https://user-images.githubusercontent.com/12330493/27473989-91c15418-5809-11e7-94e4-5309336f0c72.png">
<img width="1280" alt="screen shot 2017-06-23 at 11 45 18" src="https://user-images.githubusercontent.com/12330493/27473990-91c3a4a2-5809-11e7-87d4-06e2663670a3.png">
<img width="1280" alt="screen shot 2017-06-23 at 11 45 27" src="https://user-images.githubusercontent.com/12330493/27473991-91c52480-5809-11e7-806f-a16bc051aec3.png">
