### ISSUE TITLE
First name is not mandatory for Request a demo popup

### ISSUE THREAD

**Issue by AlexandrUrita** [AdTechMedia/adtechmedia-website#217]
Steps to reproduce:
1. Navigate to Adtechmedia web site
2. Click on REQUEST A DEMO button
3. Enter valid email
4. Do NOT fill Name field
5. Click on GET STARTED button

Expected Result: Error message should be displayed -> Please fill First Name field

Actual Result: User can submit a form w/o entering Name

Note: User can enter only Letters(UPPER and lowercase) and Numbers (1234567890)
![request a demo](https://user-images.githubusercontent.com/27765884/27220571-4a05cb02-528e-11e7-8724-17acf63469d8.gif)

**Comment by icovali** [comment]
As per initial requirements and custom MailChimp configuration code added to the project, the `Name` field is not set as required. 
@ivignan could you please check if the requirements were altered

**Comment by irca20** [comment]
Hi, I've inlcuded in the mailchimp first name as required field. Let me know if you need more help with this.


<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//mitocgroup.us11.list-manage.com/subscribe/post?u=13a7a5fca813b378c24ec9fe3&amp;id=84c8a84bc7" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe to our mailing list</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_13a7a5fca813b378c24ec9fe3_84c8a84bc7" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-03 at 15 29 02" src="https://user-images.githubusercontent.com/12330493/27795029-3295dc0a-600d-11e7-98f1-746e1fc19984.png">
