### ISSUE TITLE
Submit button allow to send not full data

### ISSUE THREAD

**Issue by AlexandrUrita** [AdTechMedia/adtechmedia-website#218]
Steps to reproduce:
1. Navigate to adtechmedia.io web site
2. Navigate to Contact page
3. Fill not valid data, exception only for email form. Example:
Name - 1
Phone - 1 
Email - a@a.c
Message - 1
4. Click on SUBMIT button (several times and quick)
4.1 If Captcha enabled - answer the question and click on SUBMIT button (several times and quick)

Expected result: Warning message should be displayed that necessary data is not filled

Actual result: Confirmation message is displayed. Fields are refreshed 

![contact forms](https://user-images.githubusercontent.com/27765884/27222066-8c936b3c-5293-11e7-8151-c7689ffd64c4.gif)

**Comment by AlexandrUrita** [comment]
@ddimitrioglo Updates: Checked with Alex V. Data transmits to mitocgroup email

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-03 at 15 25 25" src="https://user-images.githubusercontent.com/12330493/27792772-f14ad600-6003-11e7-80bb-b45aa247c316.png">
