### ISSUE TITLE
Add validation for "Email address" field

### ISSUE THREAD

**Issue by veronicamacovei** [AdTechMedia/adtechmedia-website#223]
Website Page - https://www.adtechmedia.io/calculator-result/

**Email address** field
_Actual result_: This field is valid when I insert:

- Email with a dot on the first position 

<img width="393" alt="screen shot 2017-06-15 at 8 36 03 pm" src="https://user-images.githubusercontent.com/17923747/27280121-84f9d466-54ef-11e7-9aaa-0559c83d3089.png">

 - Dot is missing from email

<img width="367" alt="screen shot 2017-06-15 at 2 37 55 pm" src="https://user-images.githubusercontent.com/17923747/27280249-e7bf26aa-54ef-11e7-8e0f-8e2c0f907384.png">

- Allows  other characters except (digit, underscore, and dash)

<img width="192" alt="screen shot 2017-06-19 at 1 10 31 pm" src="https://user-images.githubusercontent.com/17923747/27280477-b856082e-54f0-11e7-8aa9-e4f965b261f7.png">

- Allows double dots

<img width="258" alt="screen shot 2017-06-15 at 8 49 25 pm" src="https://user-images.githubusercontent.com/17923747/27280573-0dadbd08-54f1-11e7-8590-bddc6d13b217.png">

_Expected result_ :  Email with be invalid if:

- @ is not present
-  mysite@.com.my [  (Top Level domain) can not start with dot "." ]
-  @you.me.net [ No character before @ ]
- .mysite@mysite.org [ an email should not start with "." ]
- mysite()*@gmail.com [ here the regular expression only allows character, digit, underscore, and dash ]
- mysite..1234@yahoo.com [double dots are not allowed]
- mysite@gmail [Dot is missing]

**Comment by avozicov** [comment]
**Test Passed** for all described scenarios 
Notification message is triggered when request is accepted with invalid email 

<img width="1280" alt="screen shot 2017-08-17 at 17 05 12" src="https://user-images.githubusercontent.com/12330493/29416370-827e6d8e-836e-11e7-9121-deaacadfeb2e.png">
