### ISSUE TITLE
Add validation for "My name is" field

### ISSUE THREAD

**Issue by veronicamacovei** [AdTechMedia/adtechmedia-website#224]
Website Page - https://www.adtechmedia.io/calculator-result/

Field **My name is** 
_Actual result_: No validation
_Expected result_ : Only letters, max 70 characters, allow space

**Comment by avozicov** [comment]
**Test Failed**
Request can be submitted if the following requirement has not been met:
- `max 70 characters

**Comment by avozicov** [comment]
Test **Passed**
My name field does not allow to introduce more than 70 characters
