### ISSUE TITLE
Challenges page redesign

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#235]
Page affected: `/challenges/`
Design: https://xd.adobe.com/view/50d8e7ad-b3de-479c-8219-6664d2701809/screen/7713b3b7-6e1c-46ec-b9d5-48c2249960c9/Challenges/

**Comment by icovali** [comment]
@irca20 @ivignan There are lots of `learn more` buttons in the design, could you please help me with corresponding links for each button?
There is also need for content changes as per Eugene's comment:
https://github.com/MitocGroup/www/issues/163#issuecomment-309725005

**Comment by icovali** [comment]
As for initial implementation, the links were added as follows:
https://github.com/MitocGroup/www/issues/163#issuecomment-312207443

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-03 at 16 36 53" src="https://user-images.githubusercontent.com/12330493/27795353-71d12d1a-600e-11e7-855d-cc7d7a9a5bdd.png">
<img width="1280" alt="screen shot 2017-07-03 at 16 36 57" src="https://user-images.githubusercontent.com/12330493/27795355-71d432bc-600e-11e7-9f9f-eac8677b0256.png">
<img width="1280" alt="screen shot 2017-07-03 at 16 37 01" src="https://user-images.githubusercontent.com/12330493/27795354-71d41b56-600e-11e7-9030-5250f48253ad.png">
<img width="1280" alt="screen shot 2017-07-03 at 16 37 03" src="https://user-images.githubusercontent.com/12330493/27795356-71dc4808-600e-11e7-8e4f-6173dfa24dd7.png">

Note:
- there may be some changes to "Mark Thomson quote" which will be added in separate task
