### ISSUE TITLE
WordPress plugin page redesign

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#236]
Page affected: `/wordpress-plugin/`
Design: https://xd.adobe.com/view/d1cb69f3-db0d-4775-add1-20e963cc5e51/

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-03 at 17 09 34" src="https://user-images.githubusercontent.com/12330493/27796544-0d0360ec-6013-11e7-9b17-4804f1188403.png">
<img width="1280" alt="screen shot 2017-07-03 at 17 09 44" src="https://user-images.githubusercontent.com/12330493/27796545-0d06dc7c-6013-11e7-8cc4-fd9a45334c61.png">
