### ISSUE TITLE
Drupal module page redesign

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#237]
Page affected: `/drupal-module/`
Design: https://xd.adobe.com/view/d1cb69f3-db0d-4775-add1-20e963cc5e51/screen/1be19d48-6861-4335-bbcb-f8ae9ea4d27f/drupal-module/

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-03 at 18 12 51" src="https://user-images.githubusercontent.com/12330493/27798809-55d953c8-601b-11e7-8b0a-45ff7f9b126e.png">
<img width="1280" alt="screen shot 2017-07-03 at 18 13 11" src="https://user-images.githubusercontent.com/12330493/27798810-55df9a26-601b-11e7-8900-c0b85fdc9b59.png">
