### ISSUE TITLE
Add video#2 on home block

### ISSUE THREAD

**Issue by mgoria** [AdTechMedia/adtechmedia-website#24]
- Let’s add another slide on home block that will say “OUR TECHNOLOGY IS WHITE LABELED AND DATA DRIVEN” and below play button that launches video#2, while in background runs video#2 without sound

**Comment by mgoria** [comment]
@eistrati Could you pls provide us the link to the video ?

**Comment by eistrati** [comment]
@mgoria https://youtu.be/DiBh8r3lPpM

**Comment by eistrati** [comment]
Verified.
