### ISSUE TITLE
Blog post in footer showing no description

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#251]
<img width="863" alt="screen shot 2017-06-30 at 11 44 50" src="https://user-images.githubusercontent.com/8668196/27728225-1b1519ae-5d8a-11e7-9fa7-d048c46f5dbf.png">

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-03 at 15 17 58" src="https://user-images.githubusercontent.com/12330493/27792691-a1f57a6a-6003-11e7-9e97-9a6ea26006a0.png">
<img width="1280" alt="screen shot 2017-07-03 at 15 22 35" src="https://user-images.githubusercontent.com/12330493/27792690-a1f317d4-6003-11e7-8689-c43b4fe53ebf.png">
<img width="1280" alt="screen shot 2017-07-03 at 15 23 17" src="https://user-images.githubusercontent.com/12330493/27792692-a1f60872-6003-11e7-87d2-54b574f9de12.png">
