### ISSUE TITLE
Green colored background is displayed around embedded youtube player 

### ISSUE THREAD

**Issue by avozicov** [AdTechMedia/adtechmedia-website#255]
_Steps to reproduce:_
- Navigate to https://www-dev.adtechmedia.io/wordpress-plugin/ link
- Scroll down and focus on "Embedded youtube player"

_BUG:_
- Green colored background is displayed around embedded youtube player 

_Note:_
- This fix should be also applied on "drupal-module" page

_Please refer to attachment for more details:_
<img width="729" alt="screen shot 2017-07-03 at 18 11 30" src="https://user-images.githubusercontent.com/12330493/27799370-92bab73a-601d-11e7-8b82-7187b1fb3dfb.png">

**Comment by AlexandrUrita** [comment]
FYI: Test actions cannot be performed because of the new approach of environments. Manage and website are separate in test env. Developers are working now to resolve related issues
Blocked by: https://github.com/MitocGroup/atm/issues/1107

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-07-20 at 12 23 22" src="https://user-images.githubusercontent.com/12330493/28410423-51a76186-6d46-11e7-9092-f16155630f97.png">
<img width="1280" alt="screen shot 2017-07-20 at 12 23 41" src="https://user-images.githubusercontent.com/12330493/28410424-51a81a54-6d46-11e7-8c27-411367e04863.png">
