### ISSUE TITLE
[ATM-WEB] Minify js and HTML during deepify server

### ISSUE THREAD

**Issue by ddimitrioglo** [AdTechMedia/adtechmedia-website#256]
Implement a hook which minifies js and HTML during `deepify server` command

**Comment by avozicov** [comment]
**Test Passed**
HTML 
<img width="1280" alt="screen shot 2017-07-14 at 19 13 14" src="https://user-images.githubusercontent.com/12330493/28220546-94ed9b36-68c8-11e7-9fb4-ed3e92e93eab.png">

For js please refer to the comment section in the following task
https://github.com/AdTechMedia/adtechmedia-website/issues/108
