### ISSUE TITLE
[API docs] Change api endpoint for www-test environment

### ISSUE THREAD

**Issue by ddimitrioglo** [AdTechMedia/adtechmedia-website#271]
Current behavior is that www-test swagger UI calls www-dev endpoint

**Comment by avozicov** [comment]
**Test Passed**
<img width="783" alt="screen shot 2017-07-14 at 19 05 40" src="https://user-images.githubusercontent.com/12330493/28220253-79618428-68c7-11e7-9330-8ab77318fb4e.png">
