### ISSUE TITLE
[Blog posts in Footer]: Add triple dot to truncated text

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#278]
<img width="904" alt="screen shot 2017-07-17 at 13 17 13" src="https://user-images.githubusercontent.com/8668196/28264183-79bcccb6-6af2-11e7-8bbe-2b01f3fc6244.png">

**Comment by avozicov** [comment]
**Test Passed**
<img width="1275" alt="screen shot 2017-07-25 at 11 50 08" src="https://user-images.githubusercontent.com/12330493/28563809-bf19a5ac-712f-11e7-9e33-7b1c2c2c8642.png">
<img width="1275" alt="screen shot 2017-07-25 at 11 50 52" src="https://user-images.githubusercontent.com/12330493/28563810-bf19f2c8-712f-11e7-8787-c27ba0eb047b.png">
