### ISSUE TITLE
Hotfix process improvement

### ISSUE THREAD

**Issue by ddimitrioglo** [AdTechMedia/adtechmedia-website#301]
More details [here](https://github.com/MitocGroup/atm/issues/1097)

**Comment by ddimitrioglo** [comment]
- [x] Implemented node_modules caching
- [x] Implemented lambdas caching
- [x] Implemented reusing previously compiled lambdas

**Comment by AlexandrUrita** [comment]
Was used several time new flow of hotfixes. No issues in deployment process
