### ISSUE TITLE
Infinite page load is performed when using absolute url path 

### ISSUE THREAD

**Issue by avozicov** [AdTechMedia/adtechmedia-website#311]
_Steps to reproduce:_
- Use the following absolute url path to navigate to admin component 
`https://www-stage.adtechmedia.io/admin/`

_BUG:_
- Infinite page load is performed and user can not access admin component 

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-08-04 at 12 01 13" src="https://user-images.githubusercontent.com/12330493/28962014-f9370be6-790c-11e7-8391-aa396ff6f5d4.png">

**Comment by ddimitrioglo** [comment]
Fixed in https://www-test.adtechmedia.io/admin/

**Comment by avozicov** [comment]
**Test Passed**
<img width="1280" alt="screen shot 2017-08-04 at 17 09 09" src="https://user-images.githubusercontent.com/12330493/28972275-b0e752da-7937-11e7-800c-b203c4408f51.png">
