### ISSUE TITLE
[ATM-WEB] add 'build' branch to travis.yml

### ISSUE THREAD

**Issue by ddimitrioglo** [AdTechMedia/adtechmedia-website#326]
- [x] create `build` branch
- [x] use it for PRs to `test` branch (do not lock `dev` brach during deploy)
- [x] configure travis.yml (run unit test)

**Comment by avozicov** [comment]
Test **Passed**
<img width="310" alt="screen shot 2017-08-25 at 12 04 43" src="https://user-images.githubusercontent.com/12330493/29707433-e74e47f0-898d-11e7-85e0-ad43b843d5e5.png">
<img width="521" alt="screen shot 2017-08-25 at 12 06 19" src="https://user-images.githubusercontent.com/12330493/29707435-e7620b96-898d-11e7-8a46-7bc18566004b.png">
<img width="945" alt="screen shot 2017-08-25 at 12 04 24" src="https://user-images.githubusercontent.com/12330493/29707434-e74edae4-898d-11e7-9366-70360f5e85dd.png">
