### ISSUE TITLE
Wrong endpoint for api

### ISSUE THREAD

**Issue by AlexandrUrita** [AdTechMedia/adtechmedia-website#367]
Steps to reproduce:
1. Navigate to adtechmedia site
2. Navigate to api-docs
3. Make call
4. Check for requested url for parameters

Expected result: should be pointing to prod version

Actual result: pointing to api-test
<img width="1175" alt="bug_api" src="https://user-images.githubusercontent.com/27765884/29966652-89a39694-8f1b-11e7-893e-2d3871df4829.png">

**Comment by avozicov** [comment]
Test **Passed**
<img width="633" alt="screen shot 2017-09-11 at 14 06 56" src="https://user-images.githubusercontent.com/12330493/30271845-8334c8fa-96fa-11e7-940a-603535beb1b4.png">
