### ISSUE TITLE
WP: one article 'Clinton headed to Nebraska...' is broken

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/adtechmedia-website#4]
Bug reproduces only for `Clinton headed to Nebraska, which could provide exactly 1 of 270 electoral votes` article.

See attached: content is not blurred and widget is not displayed. Multiple errors are displayed in console.

![screenshot from 2016-09-26 14 52 16](https://cloud.githubusercontent.com/assets/10956412/18837419/62f99cc0-840c-11e6-9eb4-97c2b22bf08f.png)

**Comment by eistrati** [comment]
Verified.
