### ISSUE TITLE
Links from nytimes demo pages are broken

### ISSUE THREAD

**Issue by mgoria** [AdTechMedia/adtechmedia-website#42]
![screen shot 2016-10-18 at 7 49 40 pm](https://cloud.githubusercontent.com/assets/2959952/19487554/0b4d42b2-956c-11e6-95fc-baa8b837d11e.png)

Prev fix. https://github.com/MitocGroup/atm/commit/05b5a67418ee99da579928ab41de676ac3eee4b9

**Comment by eistrati** [comment]
Verified.
