### ISSUE TITLE
Try Now Block

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#52]
![5219ded4-afe9-11e6-91f4-23bd3801aea0](https://cloud.githubusercontent.com/assets/8668196/20529045/6133b540-b0d7-11e6-9568-5b29a59d0721.JPG)
![57a20f52-afe9-11e6-985d-0cc1bbc727fa](https://cloud.githubusercontent.com/assets/8668196/20529047/65be52aa-b0d7-11e6-9586-c55ba7bdbed6.JPG)

**Comment by icovali** [comment]
Please use `issue_52` branch with block's changes

**Comment by eistrati** [comment]
Not relevant anymore.
