### ISSUE TITLE
"Register" and "Login" links lead to dev environment instead of prod

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/adtechmedia-website#64]
1) Open `https://www.adtechmedia.io/case-studies/` page
2) Click on "Register"/"login" link

See attached: links lead to `www-dev.adtechmedia.io...` instead of `www.adtechmedia.io...`

<img width="1280" alt="screen_shot_2017-03-03_at_5_47_40_pm" src="https://cloud.githubusercontent.com/assets/10956412/23557914/6c6fbe4c-003a-11e7-8c0c-3d5f156e0aa8.png">

**Comment by avozicov** [comment]
Test actions should be performed on Prod Env. 
Task will be tested after Prod deploy.

**Comment by eistrati** [comment]
Verified.
