### ISSUE TITLE
Menu scroll on mobile

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#67]
Please fix menu items scrolling on mobile

<img width="599" alt="menu-scroll" src="https://cloud.githubusercontent.com/assets/8668196/23651990/f5829b6c-032f-11e7-936c-ab90b899e286.png">

**Comment by avozicov** [comment]
I will test this task and will update the status once the code will be deployed to dev environment

**Comment by avozicov** [comment]
There is still issue reproducing on small ios devices: 
- Scroll can non be performed inside the menu

**Comment by avozicov** [comment]
Confirmation testing will be performed after Dev deploy

**Comment by avozicov** [comment]
Confirmation testing = Failed

- Menu can not be scrolled on device's orientation change
