### ISSUE TITLE
Not Found page on larger devices

### ISSUE THREAD

**Issue by icovali** [AdTechMedia/adtechmedia-website#69]
Please stick footer to the bottom of the page

![not found](https://cloud.githubusercontent.com/assets/8668196/23653692/1a250fd0-0336-11e7-818a-879468749b27.png)

**Comment by avozicov** [comment]
Task was test on dev environment and Test is Passed.
I am moving it to resolved items but it will be retested after prod deploy during Health-Check.

**Comment by eistrati** [comment]
Verified.
