### ISSUE TITLE
Social Card Integrations

### ISSUE THREAD

**Issue by ivignan** [AdTechMedia/adtechmedia-website#80]
The goals is to control/suggest the sharing image and text for 3rd party sites.
Ex. When someone shares adtechmedia.io on Facebook, it automatically detects what image to display for the post, we can influence the image that should be displayed

Reference material: https://www.quicksprout.com/2013/03/25/social-media-meta-tags-how-to-use-open-graph-and-cards/
https://blog.kissmetrics.com/open-graph-meta-tags/

**Comment by avozicov** [comment]
Confirmation testing will be performed after Dev deploy

**Comment by avozicov** [comment]
Task is blocked for testing on dev environment.
Prod deploy is required to perform confirmation testing for this implementation.

**Comment by ddimitrioglo** [comment]
@avozicov please elaborate why do we need prod deploy?

**Comment by avozicov** [comment]
@ddimitrioglo 
After discussing it with @icovali I got comment that for social card integration there was _app.id_ required, but it was generated for Prod environment (www.adtechmedia.io)

**Comment by ddimitrioglo** [comment]
ok, got you @avozicov, thanks
