### ISSUE TITLE
Website fonts

### ISSUE THREAD

**Issue by pleshco** [AdTechMedia/adtechmedia-website#97]
Some parts of website are not displayed in Futura font while this font isn't installed in OS. Also, fonts are looking not good (sharpen edges) on Windows OS
![3](https://cloud.githubusercontent.com/assets/25935288/24790906/c895c048-1b80-11e7-8b05-b11c34d9ef44.png)
![screenshot_20170407-105924](https://cloud.githubusercontent.com/assets/25935288/24791102/87b079c8-1b81-11e7-97db-0ab85ebb376a.png)

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- Required Fonts should be applied to "Header" items on Windows OS 
(Windows 7 was used to execute testing)
